version: '3'
services:
  pgdb:
    image: "postgres:14.2"
    container_name: "pgdb"
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=pwd123
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
    volumes:
     - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    ports:
    - "6379:6379"

  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - pgdb

  # celery:
  #   build: .
  #   command: celery -A parser_app worker  --loglevel=info
  #   volumes:
  #     - .:/celery
  #   env_file:
  #     - .env
  #   environment:
  #   # environment variables declared in the environment section override env_file
  #     - DEBUG=1
  #     - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
  #     - CELERY_BROKER=redis://redis:6379/0
  #     - CELERY_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - django
  #     - redis
